spring.application.name=ingesta_metrics

# 1. Connexion a PostgreSQL (Puerto 5432)
spring.datasource.url=JDBC:postgresql://localhost:5432/agente
spring.datasource.username=postgres
spring.datasource.password=AQUI_PON_TU_CONTRAST
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuration de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# 3. LA MAGIA: Esto crea las tablas autoincrement
spring.jpa.hibernate.ddl-auto=update